### ISSUE TITLE
[share] share image as file not working

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1000]
Original report [on Lemmy](https://feddit.it/post/8692732).

**Comment by Black616Angel** [comment]
Okay, I am in 1.12 and it still doesn't work for me. 
I even reinstalled the app.

Please look into it again. Other Lemmy apps can share no problem.

**Comment by diegoberaldin** [comment]
Thanks for reporting, if you have ideas and want to help you're welcome. What is weird is that in debug builds it is working whereas in release builds it is not. I initially thought it was due to some timing/concurrency issue but apparently it is not. In any way, that is not easy to debug as it seems.

**Comment by diegoberaldin** [comment]
This is solved, so we can safely closed it!
