### ISSUE TITLE
[post] Embedded images are sometimes cut off

### ISSUE THREAD

**Issue by N7-X** [diegoberaldin/RaccoonForLemmy#1015]
Embedded images are sometimes cut off in post comments.  Unfortunately this is an intermittent issue, and finding posts that have the issue is difficult. 

After digging through every post in lemmy.world while looking at a different issue, I finally found one that seems to consistently have this issue. 
[https://lemmy.world/post/16785041](https://lemmy.world/post/16785041)

Steps I took to reproduce: 
1. Navigate to [https://lemmy.world/c/ich_iel@feddit.de](https://lemmy.world/c/ich_iel@feddit.de) in web browser
2. Open/Share in Raccoon using Lemmy Redirect
3. Scroll down in the comments, and the embedded image will be only partially loaded

![EmbeddedImage](https://github.com/diegoberaldin/RaccoonForLemmy/assets/62263986/82efe1b7-dd25-456d-b633-0c17a6bca181)

**Comment by N7-X** [comment]
Ah!  It looks like this happens if there's a new line _after_ the embedded image: 

`Text before the image\n![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Raccoon_in_Central_Park_%2835264%29.jpg/220px-Raccoon_in_Central_Park_%2835264%29.jpg)
`

This displays just fine in the app

`![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Raccoon_in_Central_Park_%2835264%29.jpg/220px-Raccoon_in_Central_Park_%2835264%29.jpg)\nText after the image
`

This ends up looking like the image in the initial post. 

@diegoberaldin, do you think this is another issue with the current markdown library?

**Comment by diegoberaldin** [comment]
Yes definitely... For images *without* a newline before them I already used a workaround in #997, honestly I don't know it anything similar can be done for this case to remove the newline.

That library has some issues indeed, but for Compose multiplatorm there is not much choice.

**Comment by N7-X** [comment]
Very helpful, thank you! 

I will mess around with a test post and see if I can figure out a way to make it render properly. 
**IF** I find something, then I'll see if it's possible to create a workaround without breaking something else...

**Comment by N7-X** [comment]
Many, _many_ thanks for mentioning and linking that PR! 
You cut down a significant amount of time that I would have spent digging around. 

I forgot to mention in #1022 that I also tested comments where multiple images are embedded, such as: 
[https://lemm.ee/post/35137042/12714582](https://lemm.ee/post/35137042/12714582)

The end result should now look like this in Raccoon: 
![MarkdownWorkaround](https://github.com/diegoberaldin/RaccoonForLemmy/assets/62263986/4e39e3e0-df14-4a9b-ba8b-24675222e87b)
