### ISSUE TITLE
[account switch] appearance settings reset to default when switching account

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1023]
Originally reported by @SagXD on Matrix.

> Also found an annoying bug
> Whenever you switch accounts in Raccoon, the content and application appearance settings change back to default

**Comment by diegoberaldin** [comment]
This is not reproducible but there is actually a bug when logging in with an existing account but with a different capitalization in the user name (which on Lemmy is not case-sensitive but as long as account settings in Raccoon are concerned it is).

**Comment by SagXD** [comment]
> This is not reproducible but there is actually a bug when logging in with an existing account but with a different capitalization in the user name (which on Lemmy is not case-sensitive but as long as account settings in Raccoon are concerned it is).

But I have two account on Raccoon both have same username. 

- @sag@lemm.ee
- @sag@lemy.lol

and both also have same display user name. Is this bug is related to this?

**Comment by SagXD** [comment]
Now, I also can't reproduce it.

**Comment by diegoberaldin** [comment]
> But I have two account on Raccoon both have same username. 
> 
> - @sag@lemm.ee
> - @sag@lemy.lol
> 
> and both also have same display user name. Is this bug is related to this?


That is another bug... the pair username + instance is used to determine whether the account exists or not.


If the settings reset happened just once, the first time you logged in with the new account, this is the intended behavior of the app.

**Comment by SagXD** [comment]
> > But I have two account on Raccoon both have same username.
> > 
> > * @[sag@lemm.ee](mailto:sag@lemm.ee)
> > * @[sag@lemy.lol](mailto:sag@lemy.lol)
> > 
> > and both also have same display user name. Is this bug is related to this?
> 
> That would be another bug... the pair username + instance is used to determine whether the account exists or not.
> 
> If the settings reset happened just once, the first time you logged in with the new account, this is the intended behavior of the app.

OK I will see. If I can recreate bug.

**Comment by SagXD** [comment]
It happen again.
I have one more account @sag@xyx.tld(Not Real Username) which have no display username at all. After switching to it and switching back to my lemm.ee account, Raccoon set my appearance and content setting to default. Advance setting also set back to default.

**Comment by diegoberaldin** [comment]
Ok, I understand. I made some checks and I invite you to please wait for next week's development release, uninstall the current app, reinstall the new pre-release build and repeat the steps to see whether this is solved (at it appears to me in my tests).

**Comment by SagXD** [comment]
OK, I will.
