### ISSUE TITLE
[search] default search result category should be communities instead of posts

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1024]
Originally requested by @SagXD on Matrix.

> Explore tab should show trending communities instead of posts (or make settings to set default)

**Comment by diegoberaldin** [comment]
I agree in that most users expect to find a list of communities because most Lemmy clients do this. I am inclined to changing the default and adding an option in the advanced settings to change it as one wishes.

**Comment by SagXD** [comment]
For addition, I really like how thunder handle explore tab.

![Screenshot_20240623-132704](https://github.com/diegoberaldin/RaccoonForLemmy/assets/95903022/86f7164a-c939-44c5-9ddc-7f064633a664)
