### ISSUE TITLE
[ui enhancement] change text fields to match M3 look

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1025]
Originally requested by @SagXD on Matrix.

> Change search bar on explore tab and side bar to Material 3 look

![Screenshot_20240622-111649_20240623085352.jpg](https://github.com/diegoberaldin/RaccoonForLemmy/assets/2738294/f28dfb22-d8ac-4e2e-afc9-eb9cbc94f2a2)

![Screenshot_20240622-111700_20240623085358.jpg](https://github.com/diegoberaldin/RaccoonForLemmy/assets/2738294/c6df49be-8b2f-4a60-b6b6-3d4bfb9841c1)

**Comment by diegoberaldin** [comment]
Actually it is unclear what they are asking here, because the app is already using M3 components and the text fields - ugly as they may look - are actually matching M3 specs:

https://m3.material.io/components/text-fields/specs

**Comment by SagXD** [comment]
> ugly as they may look 

Exactly they look ugly. That's why I suggested it.
I think It should look like Thunder search bar or Moshidon search bar.

![Uploading Screenshot_20240623-132704.jpg…]()
