### ISSUE TITLE
[explore] long press on explore icon in bottom bar should open search bar

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1029]
Originally requested by @SagXD on Matrix

> Holding the explore icon should directly open in the search bar

**Comment by diegoberaldin** [comment]
Is this really an improvement in terms of user experience?

**Comment by SagXD** [comment]
> Is this really an improvement in terms of user experience?

Yea, I guess. I only use Explore Tab for searching communities. And able to directly launching search bar is very neat feature for me.

**Comment by SagXD** [comment]
Also I have suggested this because Sync for Lemmy and Moshidon both have this feature.
