### ISSUE TITLE
[profile] change profile icon in bottom bar with user avatar

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1030]
Originally requested by @SagXD on Matrix

> Profile Icon should show user profile image instead of blank people icon

**Comment by diegoberaldin** [comment]
Personally I disagree and I think having a uniform look for all bottom navigation items is a plus.

**Comment by SagXD** [comment]
> Personally I disagree and I think having a uniform look for all bottom navigation items is a plus.

I also don't know about this one. But I have seen many social media app using that's why I suggested it.

**Comment by N7-X** [comment]
Maybe this could be an optional setting, where it is turned off by default? 

I imagine most users will browse in anonymous mode or use a single account, and would likely will not dig through the settings. 
More advanced / power users will likely have multiple accounts, and _would_ probably dig through the settings to customize everything.

**Comment by diegoberaldin** [comment]
Nice idea!
