### ISSUE TITLE
[restore post/comment] unable to restore deleted items

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1031]
Originally requested by @SagXD on Matrix

> Able to restore deleted posts and comments

**Comment by diegoberaldin** [comment]
Do you mean you are *unable* to do it? Could you please provide more info about what screen you were it, what were you seeing and what happened (if anything happened) when you selected the "restore" option in the drop-down menu?

**Comment by SagXD** [comment]
> Do you mean you are _unable_ to do it? Could you please provide more info about what screen you were it, what were you seeing and what happened (if anything happened) when you selected the "restore" option in the drop-down menu?

I can't even see deleted comment and posts.


https://github.com/diegoberaldin/RaccoonForLemmy/assets/95903022/5a755d4b-8d8f-42c4-be22-2108bc997310

**Comment by diegoberaldin** [comment]
Bear in mind that deleted comments will not be visible everywhere, but only in
- community detail
- post detail
- your profile (list of posts and comments)
