### ISSUE TITLE
[inbox] long press on inbox icon should mark all items as read

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#1032]
Originally requested by @SagXD on Matrix

> Holding down the inbox should mark all notification as read

**Comment by diegoberaldin** [comment]
I don't agree partially, do you think people are used to all these long press action on navigation bar items? Moreover, there is a button in the "action" part of the top bar which does exactly this, is this really needed?

**Comment by SagXD** [comment]
Well, I don't know about other. But I have used this feature in some app.
