### ISSUE TITLE
select text

### ISSUE THREAD

**Issue by zavorra** [diegoberaldin/RaccoonForLemmy#1116]
**Is your feature request related to a problem? Please describe.**
It is not possible to highlight/select text on messages or posts. 
I find this frustrating, as an example because as a non native English speaker I use to select unknown words and search them 

**Describe the solution you'd like**
Well, enable selection/copy/search on text

**Comment by diegoberaldin** [comment]
There a quick fix: for each post or comment please open the horizontal ellipsis button `⋯` you will find a "View raw" option in the drop-down menu.

This will open a dialog from where you can see the raw Markdown source of the post/comment and in the text field you'll be able to select, copy, paste or even create a quick reply by quoting part of a previous answer.

<div align="center">
<img src="https://github.com/user-attachments/assets/fdccce11-a60d-4c7d-b178-106b6d5c2bc4" width="310" />
</div>

**Comment by zavorra** [comment]
Thanks for the workaround. In any case please keep the request open, since it would be cool to have it straight on

**Comment by diegoberaldin** [comment]
Closed by #1121 and #1125.
