### ISSUE TITLE
[feed filter] allow blocking specific domains

### ISSUE THREAD

**Issue by tsievert** [diegoberaldin/RaccoonForLemmy#1154]
**Is your feature request related to a problem? Please describe.**
Following scenario: 
You come across a post that shares a link to terribleNewsSource dot com. 
I don't want to see their content, because they are terrible.
I don't want to block the user or the community as this could be a single occurence.

Relay for Reddit had this feature if I remember correctly, and it was very handy to just block unwanted domains instead of users.

**Comment by diegoberaldin** [comment]
Yes, I understand and agree with your opinion.

This would be a client-side filter which "skips" posts having in their URL property a match with the blocked domain, and the list could be a local in-app setting tied to the current account (or the anonymous one). 

It is definitely an interesting feature an can be included in one of the next releases.
