### ISSUE TITLE
Inconsistent behavior on blurring nsfw contents

### ISSUE THREAD

**Issue by zavorra** [diegoberaldin/RaccoonForLemmy#1156]
**Describe the bug**
1) Nsfw contents are blurred only in the aggregate view (e.g. All)

2) when the body of a nsfw posts contains other images they may appear not blurred when scrolling the "All" main page. It may depends on the font size or other appearance settings

**To Reproduce**

1)
1. Scroll the "All" page until a nsfw post is shown and verify that the preview is blurred
2. Visit the community of such post and verify that nsfw contents are not blurred

2)
Don't know how to reproduce, it may depend on visual settings, just scroll the main view until some post with a nsfw album is shown and verify that no unblurred images are displayed 

**Smartphone (please complete the following information):**
 - Device: oneplus 8 pro
 - OS: android 14
 - Version latest

**Additional context**

![Screenshot_2024-07-19-10-13-56-27_aebf63743df9a850a546c1c82dfbb3e8](https://github.com/user-attachments/assets/e87f0fb2-d09a-4c65-bbc3-85b4f9d98ed4)

These are my settings

**Comment by zavorra** [comment]
Ok, I managed to get an example of issue 2 which can be posted here.

As you can see, under the first of the album, correctly blurred, image of the nsfw album the next one(s) comes out unblurred 


![Screenshot_2024-07-20-08-48-22-28_aebf63743df9a850a546c1c82dfbb3e8~2](https://github.com/user-attachments/assets/b83dde53-c53c-4133-bf28-57a827db68f0)

**Comment by diegoberaldin** [comment]
Yes I get it... the difference is due to the main "cover" image being a property of the post whereas all the other ones are embedded images in the body (and they are handled differently).

The body of posts is not shown in a feed unless you are using the "full" layout option, so this is (hopefully) not affecting many users, however I'll see whether something can be done to fix it.

**Comment by zavorra** [comment]
I would not consider this as closed because of point 1.

If you browse whatever nsfw community the previews are not blurred.

Is this a desired behavior?

**Comment by diegoberaldin** [comment]
Point 1 was actually intended, if the whole community is marked as NSFW.
