### ISSUE TITLE
Obtanium broken

### ISSUE THREAD

**Issue by donpdonp** [diegoberaldin/RaccoonForLemmy#143]
Obtainum (0.14.32) reports "Could not find a suitable release" when given Raccoon's github url. I also could not locate the project in Obtanium using search. 

![Raccoonforlemmy](https://github.com/diegoberaldin/RaccoonForLemmy/assets/13176/5ce439a4-d1c8-43b1-9d6c-12c27f7037b3)

**Comment by diegoberaldin** [comment]
Please toggle the "Include prereleases" switch, I've only published release candidates so far.
Or wait until next week because if everything goes as expected I'm planning to drop the official 1.0.0.

**Comment by diegoberaldin** [comment]
Closing due to question answered.

**Comment by donpdonp** [comment]
that worked thanks - it'd be a big help to have the README be more detailed about this.

```
- get it on [Obtainium](https://github.com/ImranR98/Obtainium/releases) by pressing Add App, putting `https://github.com/diegoberaldin/RaccoonForLemmy` in the App Source URL field, turning on Include Prereleases, then pressing Add.
```

**Comment by diegoberaldin** [comment]
Ok I'll add it! Thanks!
