### ISSUE TITLE
[post detail] reply to comments 

### ISSUE THREAD

**Issue by realeatham** [diegoberaldin/RaccoonForLemmy#268]
You can't currently reply to comments

**Comment by diegoberaldin** [comment]
The button to reply to comments is the 💬 icon in the bottom-left corner, the one besides the number of replies for each individuala comment.

**Comment by realeatham** [comment]
Thanks. I would suggest to have 2 swipe gestures on each side and add replying as one because I would never have figured that out Without being told.
