### ISSUE TITLE
[ui] Transparent navigation/status bar

### ISSUE THREAD

**Issue by pvxcooper** [diegoberaldin/RaccoonForLemmy#311]
Right now the app displays solid black bars for the navigation bar on the bottom and the status bar on the top. I think it would look better changing it to be transparent.

**Comment by diegoberaldin** [comment]
That's not as easy at it seems, maybe due to this being a KMP app, I couldn't find a way to get it to work. I've added a  parameter to the theme but no matter what you set the status and navigation bar color, it doesn't work.
