### ISSUE TITLE
[FYI] JavaSerializable approach won't work for K2

### ISSUE THREAD

**Issue by MV-GH** [diegoberaldin/RaccoonForLemmy#316]
I tried doing something similar

see https://youtrack.jetbrains.com/issue/KT-58892

**Comment by diegoberaldin** [comment]
Thanks for reporting. This will be a big issue in the future since Voyager requires screen properties to be serializable. I tried to reduce them to the smallest amount possible but sometimes they were needed (since this is an online app with no database/cache system). 

In the past, before using automatic serialization, I remember having passed strings and serializing everything manually with kotlinx-serialization-json but that was really ugly to see.

I'll either revert to that system or use a cache (maybe [store5](https://mobilenativefoundation.github.io/Store) which has multiplatform support) to pass around domain data between screens.

**Comment by MV-GH** [comment]
>  having passed strings and serializing everything manually with kotlinx-serialization-json

That's my current approach and it sucks indeed

**Comment by diegoberaldin** [comment]
As un update, this is still the recommended way as per Voyager's [documentation](https://voyager.adriel.cafe/state-restoration#multiplatform-state-restoration). I hope I don't have to rewrite the navigation entirely because it was a very convenient library, once you know a couple of gotchas.

**Comment by MV-GH** [comment]
Well its definitely on the Kotlin 2.0 roadmap see [KT-15220](https://youtrack.jetbrains.com/issue/KT-15220/Reuse-resolution-results-of-common-code-for-platform-modules-in-multiplatform-projects) which is part of [KT-54620](https://youtrack.jetbrains.com/issue/KT-54620)

Sadly I don't see any better solution. There is also [this FR](https://issuetracker.google.com/issues/315775835) for parcelable to become KMP but I doubt that is gonna happen

**Comment by MV-GH** [comment]
Too my surprise, they did end up adding support for Parcelable in KMP. see [KT-58892](https://youtrack.jetbrains.com/issue/KT-58892) or [this FR](https://issuetracker.google.com/issues/315775835)

**Comment by diegoberaldin** [comment]
I still foresee high degree of pain (and I don't think I'll be able to migrate this project to K2 at all), but that's good news for everyone else.

K2 will either be the time I drop multiplatform and convert everything to Android only or abandon this app completely.

**Comment by MV-GH** [comment]
> I still foresee high degree of pain (and I don't think I'll be able to migrate this project to K2 at all), but that's good news for everyone else.

What problems do you have? I have had no problems migrating to K2

Now they have also made it also possible to do the `Serializable` "hack", no need for the typealias dance either.

This is working for rn:

Common
```kt
expect interface JavaSerializable

data class Post(val name: String) : JavaSerializable
```

JVM

```kt
actual interface JavaSerializable: java.io.Serializable

fun main() {
    val post = Post("Hello")
    println(post)
    println(post is java.io.Serializable)
}

```

**Comment by diegoberaldin** [comment]
This is a KMP project, every other day something breaks and I have to fix it with duct tape. Wrong technology, it got me quite demotivated.

**Comment by MV-GH** [comment]
Ye, I feel ya. Lack of resources, features, everything's experimental, longstanding bugs. You can really feel that KMP (Compose) is still in its infancy. With Jerboa I am just dealing with Compose but even there I can feel it short comings. Although I do enjoy it more than Views toolkit for creating UI.

Did you choose KMP because you are also planning on making a ios version? I was looking into it, seems more and more possible as time goes on. Recently they made ViewModels, Room and resources KMP.

Regardless you are still making progress at much faster rate than I am with Jerboa.

The biggest hurdle that I have rn with KMP is that the intellisense is so goddamn slow in Intellji. Even with K2 mode enabled, and now it also occasionally freezes. With Compose I am having hard time dealing with recompositions.

**Comment by diegoberaldin** [comment]
Yes, you read my mind! I initially planned to have an iOS version too but I struggled so much with Gradle that I do not see it possible any more. I'll try with a desktop/JVM version maybe which is more feasible but I prefer making the experience nice for mobile users first so in my mind the transition would be: first make people happy on smartphones, then extending to large screens/foldables, then reuse the layout adaptations for desktop.

I am working on a very old laptop and IntelliJ/Android Studio keeps freezing. I hope with K2 performance would improve but what you say prepares me to the harsh reality. I'll have to replace my hardware!

**Comment by MV-GH** [comment]
Yeah I ordered some more RAM. Apparently 16 GB isn't enough anymore to do Intelji + Android Studio + browser. When I use the emulator things start grinding to a halt. Can't imagine you did all that on old laptop. Were your problems with Gradle because of KMP or more due to the multi module approach?

The only blocker for me to do iOS development is that I would need a Mac. I am not getting one just to code an app.

**Comment by diegoberaldin** [comment]
I would say the problem is the combination of a multi-module setup in a KMP project. Everything related to KSP is a pain.

The last blocking issue I got is for multiplatorm resource access (using the Compose 1.6.0 way of composeResources) for fonts which do not allow to load fonts from another module (but works well for drawables, just font res are giving this issue).

Everything is poorly documented, there are few examples scattered around and requires a lot of trial and error.
