### ISSUE TITLE
[post list, community detail] option to disable infinite scrolling

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#354]
It would be nice to show page separators and add a "load more" button to manually download new posts, in order to prevent the "doom scrolling" effect.

**Comment by BrianAllred** [comment]
It's interesting to see this, I came to post a bug about posts *not* infinitely loading, at least on Scaled sort. Is there something I'm missing?

**Comment by diegoberaldin** [comment]
No there actually is a pagination issue on instances with Lemmy 0.19.x. I can reproduce it, opening a new issue for that and looking into it in these days.
