### ISSUE TITLE
[Login] 2FA field partially hidden behind password field

### ISSUE THREAD

**Issue by BackHDLP** [diegoberaldin/RaccoonForLemmy#436]
Screenshot:
![Screenshot_20240110_065442.jpg](https://github.com/diegoberaldin/RaccoonForLemmy/assets/89653242/3c9f43dc-cf1c-4a85-b29a-5c7ca1448c32)

The area under the purple bar is the 2FA field.

You can still tap on it, but that's not as easy, due to the smaller size.

Closing the keyboard makes it look normal again.

This looks like a failed attempt to make space for the keyboard.

**Comment by diegoberaldin** [comment]
Thank you for reporting! :pray:
