### ISSUE TITLE
[profile] support Mastodon login

### ISSUE THREAD

**Issue by donpdonp** [diegoberaldin/RaccoonForLemmy#487]
I read the lemy-verse every day (mostly on Raccoon) but I have yet to create a single lemmy account. I want to participate with upvotes and new posts but it feels like a mistake to establish a new identity on lemmy when I have an identity on mastodon.

Raccoon could add support for logging into a mastodon account. I would curate a list of public lemmy communities that is kept in the Raccoon app. If I want to upvote or post, Raccoon would tell mastodon to take that action. This would let me participate in any public community from my mastodon identity.

**Comment by diegoberaldin** [comment]
This does not seem feasible, Lemmy instances require authentication to perform actions such as voting, adding bookmarks, etc. However, thanks to ActivityPub you can see Lemmy contents on Mastodon, so you can use your Mastodon account to vote in the copy of the content that is hosted on your Mastodon instance.

I am sorry to close this but this has stayed without activity for too long and I'm trying to prune issues.
