### ISSUE TITLE
[post list] Display post titles in bold font

### ISSUE THREAD

**Issue by reusityback** [diegoberaldin/RaccoonForLemmy#505]
Hello,

I'd argue that displaying post titles with a bold font increases readability, because it'd separate title from from text body.

![image9](https://github.com/diegoberaldin/RaccoonForLemmy/assets/98353605/7e8dba2f-7ba2-4dba-b175-de920f599321)

**Comment by diegoberaldin** [comment]
It should be already semibold but I'll check tomorrow! Thanks

**Comment by reusityback** [comment]
Thanks a lot!
