### ISSUE TITLE
Editing a post does not get saved

### ISSUE THREAD

**Issue by sling-shot** [diegoberaldin/RaccoonForLemmy#527]
Editing a post and saving it does not work. (I went via inbox) 

No error is reported and I am sent back to the post, but post remains unchanged. 

Tested with 1.7.6 version.

**Comment by diegoberaldin** [comment]
Ok I managed to reproduce it (happens on lemmy.world not on the instance I usually use). Probably due to Lemmy version, different instances have different version you fix something on one and you break the others.
