### ISSUE TITLE
switch to landscape killed whole input

### ISSUE THREAD

**Issue by s4msy** [diegoberaldin/RaccoonForLemmy#534]
To reproduce:

1. Create a post
2. Write some text
3. Switch to preview (optional, I've tested this again and its the same without this step)
4. Flip phone (90°) to landscape view
5. Everything is deleted now

Used the 1.7.7 Version from github on a Pixel 7a.

**Comment by diegoberaldin** [comment]
You are right, this can definitely be improved!

Working on in #535.
