### ISSUE TITLE
feature request: custom download locations

### ISSUE THREAD

**Issue by cyborgcatboy** [diegoberaldin/RaccoonForLemmy#572]
hewwo !!

i think that raccoon is great, but one quality-of-life feature that would be amazing is the ability to set where downloads are stored, as at the moment when i download an image on the android version, it just gets sent to my Pictures folder. 

I would like to request the ability to set a custom subfolder (e.g. `Pictures/Raccoon/`, `Pictures/mycustomsubfolder/`), as well as the option to use subfolders for each community (e.g. downloading a image from 196@lemmy.blahaj.zone gets downloaded to `Pictures/Raccoon/196@lemmy.blahaj.zone/`, `Pictures/mycustomsubfolder/196@lemmy.blahaj.zone/` [side note: does android allow the `@` character ? or would it have to be replaced with a `_` or something ?]). 

would this at all be possible?

anyway thanks for an amazing app !! - max

**Comment by diegoberaldin** [comment]
I'll include this feature for next Thursday's release!

![Android saved file](https://i.redd.it/7vwbdpdl33381.png)

**Comment by diegoberaldin** [comment]
Feature implemented!
