### ISSUE TITLE
When on the account list, back button exit the application

### ISSUE THREAD

**Issue by Porkepix** [diegoberaldin/RaccoonForLemmy#580]
When on the account list (you get from a slide or the sandwich button), see screenshot below, the back button is exiting the application when it should just close that sidebar and go back to the screen the user was before opening this menu.

Also note that sometimes (not every time), the first press on the back button does nothing and only the second exit the application.

In the end, whether it is with the first or the second press, it ends up quitting the application.

<details>
<summary>
Screenshot of the view where it happens
</summary>

![Screenshot_20240307-182217](https://github.com/diegoberaldin/RaccoonForLemmy/assets/709500/419346e0-bd90-40ac-ad2f-7a47b8187da4)

</details>

**Comment by diegoberaldin** [comment]
Thanks for the report and the detailed explanation. Seems a quick fix at first sight, I'll work on it for next Thursday's release! :pray:

**Comment by diegoberaldin** [comment]
Solved by #585
