### ISSUE TITLE
[post list] occasional text box size issues

### ISSUE THREAD

**Issue by reusityback** [diegoberaldin/RaccoonForLemmy#589]
![Screenshot_20240306-215532_Raccoon_for_Lemmy](https://github.com/diegoberaldin/RaccoonForLemmy/assets/98353605/020f19b5-3626-4472-b14d-5fa43c867ad7)

![Uploading Screenshot_20240306-215532_Raccoon_for_Lemmy.png…]()

Sometimes this happens, usually also when the user is logged out without having logged out (I guess the auth issue, I have no idea about this).

It goes away when restarting the app.

**Comment by reusityback** [comment]
I haven't seen this issue in a long time anymore, but I don't know since when.

**Comment by diegoberaldin** [comment]
@N7-X and I changed a couple of things with markdown images which may have fixed this, especially #997 and #1022.

If it does not happen any more, we can close it.
