### ISSUE TITLE
FEATURE REQUEST - Copy text including title

### ISSUE THREAD

**Issue by sling-shot** [diegoberaldin/RaccoonForLemmy#597]
For eg. to copy a joke from dadjokes, currently I need to press 3 dot menu > view raw > then press and hold to select text > copy separately for title and body. 

An option to directly copy from 3 dot menu or a further option the share menu would be welcome. The choices could be (a) copy title (b) copy body (c) copy both (d) select and copy.

**Comment by diegoberaldin** [comment]
I never thought of such a use case and I agree that the user experience is terrible, especially if you always have to copy multiple times from multiple posts...

I propose to add a new "copy" option in the 3 dots menu which will open a bottom sheet (like "share") where you can choose to either copy the title, the body or both.

If it seems acceptable to you, I can work on it for next week's development release (it will be included in the April production release).

**Comment by sling-shot** [comment]
That will be good.
