### ISSUE TITLE
[markdown] slash displaying when escaping characters

### ISSUE THREAD

**Issue by nightgolfer** [diegoberaldin/RaccoonForLemmy#613]
When escaping a character with backslash while writing a comment, such as an asterisk \* or other markdown related characters, the slash gets displayed in the final comment.

_final comment display_
![Screenshot_2024-03-19-08-41-17-02_aebf63743df9a850a546c1c82dfbb3e8.jpg](https://github.com/diegoberaldin/RaccoonForLemmy/assets/32328229/92c0da28-bb3a-4c91-9ca0-bef9b0f9776b)

_comment edit mode_
![Screenshot_2024-03-19-08-45-25-39_aebf63743df9a850a546c1c82dfbb3e8.jpg](https://github.com/diegoberaldin/RaccoonForLemmy/assets/32328229/f4dad06a-7acc-4e8f-a6eb-6db72085a3d5)

_raw mode_
![Screenshot_2024-03-19-08-45-47-33_aebf63743df9a850a546c1c82dfbb3e8.jpg](https://github.com/diegoberaldin/RaccoonForLemmy/assets/32328229/0f633ec0-07c0-4f05-a57d-0b49332177a2)

Expected behavior is:
- Escaped character gets displayed.
- Escaped character gets ignored by markdown parsing.
- Backslash escape character is not displayed.

**Comment by nightgolfer** [comment]
That sounds like a good idea! I'm not well versed in any of the components used (barely Git, for that matter 😅), so hadn't thought about there being an upstream.

I've tentatively switched to Raccoon from Voyager (no more 0.18 support in PWA = no Beehaw support), and I really like what you've done so far, impressive amount of features! 

Also, no small feat! I think I've tried most of the Lemmy clients available on Android, and honestly didn't think I'd be able to find a replacement for Voyager.

I'm a bit busy with a big project at the moment, but I have a ton of feedback and suggestions for Raccoon, and would love to help where I can. I don't know anything about Kotlin, but I can try to do stuff like upstream bug reports of that helps 👍 I'll try to carve out some time in the near future.

**Comment by diegoberaldin** [comment]
Ok, even leaving feedback is a great contribution, I encourage people to tell openly what they would like to see improved but either there are no users or they are very little talkative :joy:
I'll triage requests and little by little address them in weekly builds.

If you want to contribute with PRs, of course, you're more than welcome but we are not in a hurry... and for myself I plan to continue working on this project at least for this whole year.

**Comment by nightgolfer** [comment]
I'll do my best 🙂👌

I think PRs require I know how to code, right? 😅

I'll look at it and see, maybe I can sus something out, but I only know python, and not all that well, I'm mostly at the "troubleshooting cGPT code" stage 😁

One thing I'm sorry missing is the ability to hide read posts, but I'll make a proper Issue for it 👌 Unless it's already there and I just can't find it 🤔

**Comment by diegoberaldin** [comment]
Yes it's there, under the "+" floating action button in any post list screen (home or community detail).

You can mark posts as you scroll from the settings screen or they are considered read after you open them or vote them.
