### ISSUE TITLE
Post submission window always requests text

### ISSUE THREAD

**Issue by Mannivu** [diegoberaldin/RaccoonForLemmy#632]
I was trying to share a URL in a community but Raccoon wouldn't let me post it without adding text (even though it's not required, since with Voyager I was able to put just the link).
![Screenshot_2024-03-25-18-47-47-865_com github diegoberaldin raccoonforlemmy android](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/25c6067d-73bb-4284-9f52-f52cebc9d3d2)

**Comment by diegoberaldin** [comment]
Sorry, you are definitely right! The `body` property is optional in the create post request. I'll fix it immediately!

**Comment by Mannivu** [comment]
Than you!
