### ISSUE TITLE
Flashing default screen when no connection

### ISSUE THREAD

**Issue by cyborgcatboy** [diegoberaldin/RaccoonForLemmy#652]
if i open fluffychat when i hav no internet connection, on the default post list screen, if u wait a bit it starts switching rapidly between the no connection label and the loading post blockouts. it only sometimes happens, so can be hard to reproduce.
its probably not that a high priority bug, as it seems to be only cosmetic, and id say unlikely to trigger epilepsy (though i am nowhere near a doctor)

**Comment by diegoberaldin** [comment]
Thanks for the report, I'll look into it...
