### ISSUE TITLE
Image not fully loaded

### ISSUE THREAD

**Issue by Mannivu** [diegoberaldin/RaccoonForLemmy#656]
I've been using Raccoon for some time now, but I've noticed that, compared for example with Voyager, Raccoon doesn't load images in full. See [this post](https://feddit.it/post/6766666) for an example:

This is the the maximum zoom on the image loaded by Raccoon
![World map with band names on it](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/a331b662-14d8-42bf-ad94-ba5c0db36a15)

This is the the maximum zoom on the image loaded by Voyager
![World map with band names on it](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/8b691076-d832-4c22-b5bc-8d0866716f3c)

**Comment by diegoberaldin** [comment]
Yes, you're right, there are some issues with the image screen (and I could reproduce them on this post, thanks for the detailed report).

I'm on it!
