### ISSUE TITLE
"Full height images" settings doesn't seem to do anything

### ISSUE THREAD

**Issue by Mannivu** [diegoberaldin/RaccoonForLemmy#657]
I've been playing with setting of the app, but the "Full height images" setting doesn't seem to do anything at all (or maybe I havent understood what it is supposed to to).

**Comment by diegoberaldin** [comment]
If the option is disabled, images are capped to a height of 200dp in post lists (e.g. home, community detail, user detail) and post detail, otherwise they are free to expand to whatever height according to the original aspect ratio. The behaviour is exemplified in the "Content Appearance screen" in the image below the option.

The option has no effect on comments and in embedded images (i.e. images that are in the post text and not in the URL of posts of image type).

**Comment by Mannivu** [comment]
The example post however doesn't change when the setting is enabled or turned off.

![Screenshot of Raccoon settings with "Full height images" setting turned off](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/6b68453d-a613-4e50-b4c3-24a1724139bd)

![Screenshot of Raccoon settings with "Full height images" setting turned on](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/954ac48a-c06f-48a8-a7f6-d96aeebffbe3)

**Comment by diegoberaldin** [comment]
This has only effect with the "Card" and "Full" layout, in "Compact" (actually!) it has no effect either. I should remove the option when you select the "Compact" post layout because it is misleading and confusing... you're right again!

**Comment by Mannivu** [comment]
Oh, that explains it. Thanks for clarifying that. However, I think that cropping image in compact could be helpful too, so that post height is always the same (see comparison with Voyager below)

![Screenshot_2024-04-07-10-40-26-741_com github diegoberaldin raccoonforlemmy android](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/924142e1-4b08-4d57-8e63-836cbd6b51cb)
![Screenshot_2024-04-07-10-40-38-242_app vger voyager](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/95a8befd-e1e6-4d30-bb76-0b32aaefb736)

**Comment by diegoberaldin** [comment]
Aaaaargh! That makes sense... I'll reopen, fix and close it again. I thought in Compact mode images had fixed dimension but I realized I only set a proportional width and left the automatic height (which leads to not cropping).

**Comment by Mannivu** [comment]
Thank you (sorry I'm making you work on a Sunday).

**Comment by diegoberaldin** [comment]
No worries, I didn't have anything to do, except now I'd better get ready for an Italian Sunday lunch :sweat_smile:

**Comment by Mannivu** [comment]
Stessa cosa, buon pranzo!

**Comment by diegoberaldin** [comment]
Grazie, altrettanto!
