### ISSUE TITLE
visualization of a video in compact mode looks incorect

### ISSUE THREAD

**Issue by lgasp** [diegoberaldin/RaccoonForLemmy#665]
I have set the compact view for post, and everything looks correctly , excluding this post -> https://feddit.it/post/6973409

What's wrong? It's a post from mastodon containing a video and:

- the preview is not small and on the right side but it's as large as the screen and below the title
- the video reproduction starts automatically
- below the video preview and before the next post there is a big empty spac

![ResizedImage_2024-04-08_10-36-59_6349](https://github.com/diegoberaldin/RaccoonForLemmy/assets/3661279/7190f215-eccb-4ad0-91e8-8c59e8576fe8)

My system:

- Fairphone 4, android 13
- Racoon 1.9.0 from izziondroid repo

**Comment by diegoberaldin** [comment]
The fix is easier than expected, which doesn't happen EVER in real life...

![Screenshot_2024-04-08-21-16-58-420_com.github.diegoberaldin.raccoonforlemmy.android.dev.jpg](https://github.com/diegoberaldin/RaccoonForLemmy/assets/2738294/7713c199-5d5b-4a8a-ba46-05cde0955300)
