### ISSUE TITLE
[post creation] Add autofill option

### ISSUE THREAD

**Issue by Mannivu** [diegoberaldin/RaccoonForLemmy#704]
When creating a post with a link an autofill option for the "Title" field would be very useful.

`Sorry if I always bring Voyager as a comparison, but that's my backup app.`
<img alt="Voyager's Add a post view" src="https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/8cd6fa91-6d1e-4622-a32f-2c2e26cdb472" width="300"/>

**Comment by diegoberaldin** [comment]
Ok I'll look for into it, I don't know whether they just get the content at the URL and, if it is a text/html response they parse it and take one of the headers.

**Comment by Mannivu** [comment]
I too am not really sure how that work. I can tell you that with the link I used for that post the "Autofill" function gave an error (I don't think it's useful, it's more a fun fact).

**Comment by diegoberaldin** [comment]
It's an open source project so I'll have a look at the code... even in Raccoon it'll be a "best effort" attempt if I do it in the way I have in mind...

**Comment by keforbes** [comment]
For what it's worth, it looks like Jerboa is using this:
```
import it.vercruysse.lemmyapi.v0x19.datatypes.GetSiteMetadata
import it.vercruysse.lemmyapi.v0x19.datatypes.GetSiteMetadataResponse
```
https://github.com/LemmyNet/jerboa/blob/5c0396862d5c0f09a2e884c670b4b22ddd76f913/app/src/main/java/com/jerboa/model/CreatePostViewModel.kt#L12

```
            is ApiState.Success ->
                MetaDataRes(res.data.metadata.title, false)
```
https://github.com/LemmyNet/jerboa/blob/5c0396862d5c0f09a2e884c670b4b22ddd76f913/app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt#L118

**Comment by diegoberaldin** [comment]
I see... they are using [this](https://join-lemmy.org/api/classes/LemmyHttp.html#getSiteMetadata) Lemmy API which does the job for you! Wonderful! It makes things a lot easier... have I already said "when in doubt, always look at the Jerboa for Lemmy?"
