### ISSUE TITLE
App under statusbar

### ISSUE THREAD

**Issue by Pietro395** [diegoberaldin/RaccoonForLemmy#705]
The top of the app remains below the Android statusbar on "Posts" section

Pixel 6a
Android 14
GrapheneOS

<img src="https://github.com/diegoberaldin/RaccoonForLemmy/assets/50447537/05a1dcdb-529d-47a6-9994-786343c60be2"  width=50% height=50%>

**Comment by diegoberaldin** [comment]
Thanks for the report, I could reproduce it on a Pixel 6a too (on Android 14), it happens only if "edge to edge" is enabled in the Advanced settings screen, I'll work on it for this week's release.
