### ISSUE TITLE
[post] open URL instead of thumbnail image

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#732]
Original report [on Lemmy](https://feddit.it/post/7437032).

**Comment by pfaca** [comment]
It would be nice if videos (not youtube, because it already launches the YT/NewPipe APP) could open in a "video viewer" instead of having to follow the link to the site. Eternity does this.

**Comment by diegoberaldin** [comment]
Better opening a separate issue for videos, I'll do it to track it separately because that's another kind of job and I'll probably do it later.
