### ISSUE TITLE
[markdown] images (embedded) are not clickable and do not follow "autoload" setting

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#734]
Original report [on Lemmy](https://feddit.it/post/7437032).

**Comment by N7-X** [comment]
I think this is actually resolved - just tested the linked post in the original report, with the embedded image, and it did respect the setting and open in the viewer to zoom and pan. 

You _do_ have to select "load" each time you open the image, return to the post, etc. so I'm thinking that is either part of the cache issue #988 or a check needs to be added for if an image is already cached and override auto load default if yes.

**Comment by diegoberaldin** [comment]
I confirm this is actually solved by #997 and #1022.
