### ISSUE TITLE
[feature-request] Open URLs in internal browser but using external browser engine

### ISSUE THREAD

**Issue by pfaca** [diegoberaldin/RaccoonForLemmy#735]
Right now, we can open URLs in the internal browser or in the external browser, but some APPs offer a 3rd option (Eternity calls it "Custom Tab"), where it opens the URL inside the APP but using the external browser engine.

**Comment by diegoberaldin** [comment]
I see, they are using a [CustomTabsIntent](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent).

I'll add it if it is supported, ok.
