### ISSUE TITLE
[favourites] Confirmation prompt when adding favourites

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#745]
Current behaviour:
- Keyboard pops up after adding a community to favourites

Expected behaviour:
- Pop-up prompt saying the community has been added to favourites

Version:
1.10.0-20240501-pre / Android 14 One UI 6.1

**Comment by diegoberaldin** [comment]
I assume you are referring to the "Manage subscriptions" screen and not the community detail. I can't seem to be able to reproduce the keyboard issue but will look into it. Definitely adding a confirmation message when an item is added or removed to/from favorites.

**Comment by cloudlessx** [comment]
@diegoberaldin I found the way to reproduce the issue

1. Go to "home" (post list)
2. Tap the "main menu" (hamburger button at upper left)
3. Tap search (so you have the keyboard open)
4. Tap on the community from the search results
5. Tap the 3-dot menu button from the upper right
6. "Add to favorite"

Keyboard pops back up after adding to favorite. I think that is caused by the keyboard pop up during the search.

**Comment by diegoberaldin** [comment]
Thanks, now I understand it! Can't reproduce on all devices but I think I nailed it down.
