### ISSUE TITLE
[UI] Wasted blank space at the top of most pages

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#748]
Current behaviour:
- Blank space at the top of the screen, on all pages (post list, post, profile, settings)

Preferred behaviour:
- Remove the blank space

Version:
1.10.0-20240501-pre / Android 14 One UI 6.1

![raccoon](https://github.com/diegoberaldin/RaccoonForLemmy/assets/159134845/9cec3ac1-1fe4-4400-b054-3d27a0f64f90)

**Comment by diegoberaldin** [comment]
Does this happen with the "Edge to edge" option enabled or disabled? Could you please specify which Android version are you seeing this on?

**Comment by cloudlessx** [comment]
Happens only when Edge to Edge is enabled.
Android 14 / One UI 6.1
