### ISSUE TITLE
[Action Button] A better icon for the action button

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#749]
Current:
The current icon used for the action button is the location icon

Preferred icon:
Overflow/hamburger icon
![proxy-image](https://github.com/diegoberaldin/RaccoonForLemmy/assets/159134845/5c31dae1-e1ff-4f93-a0e6-4c723b4e1c2e)

**Comment by diegoberaldin** [comment]
Do you mean the floating action button in the bottom right corner of the screen?

**Comment by cloudlessx** [comment]
Yes the floating button. Sorry I should have mentioned that. By the way can you change the background colour of the menu text? The black background is too similar to the post/comment background and hard to notice the menu text.

**Comment by diegoberaldin** [comment]
Yes, sure! On it!

**Comment by cloudlessx** [comment]
Sorry I just realised that the hamburger icon is already being used for the main (top-left) menu. It might be ok as most users would probably understand the purpose of the floating icon. But you can consider

a) Replace the top-left menu icon with the user avatar, or

b) Replace the floating button icon with the "+" icon, which seems to be a popular choice for many apps for "extra" actions

**Comment by diegoberaldin** [comment]
I had a plain "+" before, but people started objecting it conveys the wrong idea of creating a new content whereas in monster cases it just has other actions like "clear read contents", "start lazy mode" or "go back to top".

**Comment by diegoberaldin** [comment]
Ok, I'll change again and hope no one notices :wink:
