### ISSUE TITLE
[post] Spoiler tag not handled in post content

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#767]
Current behaviour:
Spoilers are only handled in comment but not in posts.

Expected behaviour:
Spoilers should be handled the same way in comments and in posts.

Example:
https://sh.itjust.works/post/17190976

![Screenshot_20240504_082318_Raccoon](https://github.com/diegoberaldin/RaccoonForLemmy/assets/159134845/378b1a5e-00a2-469a-b22f-571681cb35c4)

**Comment by diegoberaldin** [comment]
Seen it yesterday evening, will have a look on it. Thanks!
