### ISSUE TITLE
[post] Overflow menu should show more actions

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#769]
Current behaviour:
Overflow menu at the top of the screen showing only "search in comments"

Preferred behaviour:
Overflow menu should show all relevant actions including share, copy to clipboard etc. Like the overflow button at the bottom of post details. 

Example:
![Screenshot_20240504_083453_Raccoon](https://github.com/diegoberaldin/RaccoonForLemmy/assets/159134845/b016a556-d253-4f2e-8049-e8ebb311bc79)

**Comment by diegoberaldin** [comment]
I think I get what you mean: in the post detail screen I put the post card with a footer and in this footer there is a drop down menu (with "Share", "Copy to clipboard", "View raw", "Cross-post" and "Report") but these actions are referred to the post so the main "subject" of the screen, this means that **instead** of using the footer menu I should use the action menu in the top bar.

If this is the idea, I like it and I would completely **remove** the menu in the footer (only in post detail, of course) and move everything to the screen menu in the top bar.

**Comment by cloudlessx** [comment]
Yeah that's the idea. But I can't decide whether to remove the footer button.  It might be a good idea to leave it there for consistency with the post list.

**Comment by diegoberaldin** [comment]
Ideally there should be a single entry point to the any action in the same screen so I am against duplicating them. I can move all the actions except "View raw", which is the only one consistently there (even in the create post screen). What do you think about this idea?

**Comment by cloudlessx** [comment]
Let's remove the footer button. The top menu is easier to access anyway. If we keep both but with different functionalities, it would be difficult to distinguish between them.

**Comment by diegoberaldin** [comment]
Agree, thank you for your suggestion (really appreciated)! :pray:
