### ISSUE TITLE
[post] Edit button incorrectly shown on uneditable posts

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#770]
Current behaviour:
Edit button shown on some posts even though I am not the author.  This seems to be random/intermittent. 

Example:
https://lemmy.world/post/14914738

![Screenshot_20240504_084318_Raccoon](https://github.com/diegoberaldin/RaccoonForLemmy/assets/159134845/12b859bd-2a54-440a-8959-243c7b9fdf64)

**Comment by diegoberaldin** [comment]
That icon is not the "Edit" button it's just an indicator that the post has been edited by the original author. The icon is misleading, I agree, and I should look for a better one.

**Comment by cloudlessx** [comment]
Perhaps use text instead of icon, for example "Edited 2 hours ago".

**Comment by diegoberaldin** [comment]
I prefer using an icon to avoid too much text, but I'll switch the small clock icon to an "update" (Material icons) which does the trick.
