### ISSUE TITLE
[side bar] Add a close button to the side bar

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#771]
There is no button to close the side bar (info panel). The only way to close it is to slide right, which wasn't obvious to me. 

Preferred behaviour:
Add a floating close button 

![Screenshot_20240504_092545_Raccoon](https://github.com/diegoberaldin/RaccoonForLemmy/assets/159134845/67073361-2094-4a5b-b90a-18cdcf745af2)

**Comment by cloudlessx** [comment]
Wow you are on fire. Thanks.

You might have done it already, but please make sure you implement this for user info pane in addition to the community info pane. Not sure if there are other places requiring this.

**Comment by diegoberaldin** [comment]
Yep! Done for both panels, they should be consistent with each other. Thanks for pointing it out.
