### ISSUE TITLE
[compose] blank space above keyboard

### ISSUE THREAD

**Issue by diegoberaldin** [diegoberaldin/RaccoonForLemmy#772]
Original report [here](https://alexandrite.app/feddit.it/post/7592771).

**Comment by diegoberaldin** [comment]
Still happening, according to the original reporter.

**Comment by MV-GH** [comment]
FYI I had issues like this in Jerboa too. In Jerboa it was because of edgeToEdge and we had padding modifier on a navhost. I moved the  padding to be on a the box in the navhost and that solved it

**Comment by diegoberaldin** [comment]
Hi Maarten and thanks! So the culprit may be the `.imePadding() `modifier applied to the `Scaffold` instead of on its content? I'll try and see what happens if I move it!

**Comment by MV-GH** [comment]
For Jerboa, it was on the navhost not the scaffolding but we don't do any imePadding on the scafffold either so that might be it. If you could reproduce it, it would be a lot easier to experiment. I'll take a looksie later

**Comment by diegoberaldin** [comment]
Unfortunately I couldn't reproduce on any device/emulator, this is the reason why I'm trying to solve it blindfolded. In any case I'll leave this open so that I'll come back to if in next releases.

Yes, the bug in the issue tracker seems quite it and people have tried like I did with `consumedWindowInsets` but to no relief.
