### ISSUE TITLE
[inbox] option to show all messages in inbox

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#773]
Current behaviour:
- only unread messages are shown

Preferred behaviour:
- option to show both read/unread messages

**Comment by diegoberaldin** [comment]
The option you may be looking for is in the "Advanced settings screen" under "Default inbox type".

**Comment by cloudlessx** [comment]
you are right.  Issue closed thanks.

**Comment by diegoberaldin** [comment]
This option was not in the "Advanced settings" screen historically, but when I decided to polish a little bit the settings I moved to the second layer because I thought only "pro" users need to fine-tune their inbox.
