### ISSUE TITLE
[inbox] pull-to-refresh should jump to the top of the list

### ISSUE THREAD

**Issue by cloudlessx** [diegoberaldin/RaccoonForLemmy#778]
Current behaviour:
Pull-to-refresh the inbox loads new messages, but stay in the current position so new messages are not visible. (when inbox is set to show all messages)

Preferred behaviour:
Jump to the top of the list after pull to refresh.

**Comment by diegoberaldin** [comment]
You're right, that's a weird thing I happened to notice myself sometimes but never realized it was a :lady_beetle: !
