### ISSUE TITLE
Big image can't be seen in full

### ISSUE THREAD

**Issue by Mannivu** [diegoberaldin/RaccoonForLemmy#789]
See [this post](https://lemmy.ca/post/20596101). In Raccoon I can't see the full image but only the middle, there's no way to open the full image, but if I download it I can download the full image.

~~Not sure if this is already fixed (I'm using 1.10.0-20240424-pre)~~ Updated to 1.10.0-20240505-pre and the issue is still present.

Add: This happens in Compacted view, it doesn't occur in Card view

**Comment by Mannivu** [comment]
Add: Enabling "Full height mode" I can see the whole image both in timelines and in post view, but clicking on the image shows only the middle part of the image.

**Comment by diegoberaldin** [comment]
Perfectly understood and reproducible, thanks for the report!
