### ISSUE TITLE
[images] Something's off with images' width

### ISSUE THREAD

**Issue by Mannivu** [diegoberaldin/RaccoonForLemmy#806]
Images now load correctly in eighth, but do not load entirely in width, they are cropped both left and right ([example post](https://feddit.it/post/7693846)).

**Comment by cloudlessx** [comment]
I think the image itself in your example was uploaded as cropped.

Can you send a screenshot of what you saw in Raccoon?

**Comment by Mannivu** [comment]
This is the image preview in the post
![Screenshot_2024-05-08-22-16-08-759_com github diegoberaldin raccoonforlemmy android](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/a6824e41-a089-437d-9639-9c7a1345b181)

This is the image I see once I tap on it in Raccoon
![Screenshot_2024-05-08-22-16-12-554_com github diegoberaldin raccoonforlemmy android](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/8542b900-9de1-455f-af32-3f69f8d5b789)

This is the same image from the same post but using Jerboa
![Screenshot_2024-05-08-22-16-28-506_com jerboa](https://github.com/diegoberaldin/RaccoonForLemmy/assets/42747216/ad6e5ef0-3731-44f6-a29d-9b66a34766d9)

**Comment by cloudlessx** [comment]
You're right. Strangely it doesn't affect all images. For example the images in https://sh.itjust.works/c/imageai appear to be fine.

**Comment by Mannivu** [comment]
Yup, I have no issue in that community.

**Comment by diegoberaldin** [comment]
I know what the problem is and I have to think about how to solve it without using the :hammer: Unfortunately there are some issues because on a multiplatform app like this it is not easy to know beforehand the aspect ratio.

**Comment by Mannivu** [comment]
Thanks!
