### ISSUE TITLE
[bug] account switching

### ISSUE THREAD

**Issue by pfaca** [diegoberaldin/RaccoonForLemmy#807]
I've found two bugs related to account switching:
- From inside the profile menu, if I change the user, the profile page does not update automatically.
-  The swipe functionality is gone altogether. The only solution is reloading the app.

**Comment by diegoberaldin** [comment]
I can not reproduce it but from your description I understand that for some reason the login call fails and you end up being "unlogged" (that is why the swipe actions, all upvotes/downvotes/save actions are disabled).

**Comment by diegoberaldin** [comment]
I think I figured out what happened, and fixed it in the above linked PR. Thanks for the report!
