### ISSUE TITLE
Virtual keyboard does not push input box up in latest version.

### ISSUE THREAD

**Issue by SleepyScribe** [diegoberaldin/RaccoonForLemmy#808]
In version 1.10, any keyboard that I use appears over the input area instead of pushing it up. Only happens when replying to comments; creating new posts seems to be unaffected.

Reproducible with both Pixel 7 Pro and Samsung Z Fold 3. Android is the latest version 14 on both devices.

Moving back to 1.9 works fine.

**Comment by diegoberaldin** [comment]
Thanks for the report, I reproduced it and solved it yesterday. I will be releasing a patch soon (1.10.1).
