### ISSUE TITLE
[Media] gifs appear vertically compressed

### ISSUE THREAD

**Issue by tsievert** [diegoberaldin/RaccoonForLemmy#832]
**Describe the bug**
Large gifs appear to be vertically compressed to a standard height in the feed.
I tested this in Card view and Full view, with max lines at Unlimited or 10. All look the same.
Full width and height image is enabled.

**To Reproduce**
1. Go to 'gifs@lemmy.world'
2. See compressed gifs

**Expected behavior**
Gifs should maintain the proper aspect ratio and not be shrunk to a default hight

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 14
 - Version 1.10.1

**Comment by diegoberaldin** [comment]
This is due to an aspect ratio being forced on videos (see the `PostCardVideo` component), which is used to render those mp4 video links.

I'll see what can be done, because I remember that all sort of weird issues arose when removing the size specification.

**Comment by diegoberaldin** [comment]
BTW: I agree that the proposed solution is not a real solution but there are some limitations due to the multiplatform nature of the project which is not easy to overcome.
