### ISSUE TITLE
[Reporting] Unsure if reports are successful

### ISSUE THREAD

**Issue by tsievert** [diegoberaldin/RaccoonForLemmy#836]
**Describe the bug**
With the current dialogue to report a post it is unclear if the report is successful.
When you tap the submit button, the screen shortly flashes, but nothing else.
No success or failure message, and you need to hit the return button to get out of the screen.

**To Reproduce**
1. Go to feed
2. Find spam post
3. Tap "...", then "Report"
4. Enter text in report form
5. Tap submit arrow
6. Screen flash but no other change

**Expected behavior**
Close the report screen and return to posts.
Success message would be optional but probably useful

**Smartphone (please complete the following information):**
 - Device: 6a
 - OS: Android 14
 - Version 1.10.1

**Additional context**
Sorry for spamming issues today

**Comment by diegoberaldin** [comment]
You are right, that form was originally a bottom sheet which closed after the completion of the operation. When I changed it to be a full screen, I forgot to handle properly the success event (only error messages are displayed in case anything goes wrong).

The same holds true for the ban user and remove content screens which are only visible to moderators.

**Comment by diegoberaldin** [comment]
I am working not only to close the screen (mandatory) but also to show an acknowledgement message which can be useful in the whole app as a notification system.
