### ISSUE TITLE
[Feature] Administrator Tools

### ISSUE THREAD

**Issue by RealStickman** [diegoberaldin/RaccoonForLemmy#841]
**Is your feature request related to a problem? Please describe.**
Instance administrators currently have no way of using their tools to remove spam or ban users for their own instance.

**Describe the solution you'd like**
Expand tools implemented in #152 for administrators

**Describe alternatives you've considered**
Using the webinterface or other apps that implement tools for administrators

**Comment by diegoberaldin** [comment]
Yes, I have a card in the project's board to remind me that admin tools are missing, but I was unsure whether anyone needed them so I was waiting to receive some request like this before looking into it.

**Comment by diegoberaldin** [comment]
Minimal set of administration actions to be added: 

- [ ] purge person
- [ ] purge community
- [ ] hide community
- [ ] purge post
- [ ] purge comment
