### ISSUE TITLE
Crash when returning from crosspost to main feed

### ISSUE THREAD

**Issue by N7-X** [diegoberaldin/RaccoonForLemmy#882]
Raccoon For Lemmy crashes, when returning from a crossposted post, to the original post, to the main feed. 

The following steps reliably reproduce the behavior: 
1. Launch Raccoon For Lemmy and open a post that has "also posted to" another instance
2. Select (one of) the crosspost link(s) - these will open as expected
3. Using either the Android "back" navigation or the "back" button at the top of the app interface returns to the original instance as expected
4. Using either the Android or interface "back" to return from the original post to the main feed will cause the app to crash

It appears that this behavior first appeared in **v1.10.0-20240501-pre** and was present in all full releases since, as well as all pre-releases tested (not al pre-releases were tested.l)

This was tested on 2x devices: 
 - Device a:  Sony Xperia 5 ii
 - AndroidOS:  Android 14 (Custom ROM:  LMODroid 5.0)
 - App Version:  1.10.2

 - Device b:  Motorola Edge Plus (2022)
 - Android OS:  Android 13 (Stock ROM)
 - App Version:  1.10.2

Additionally, I captured a logcat over adb on "device a" using the following restriction: 
`logcat | grep diegoberaldin`

Which results in: 
> 05-24 10:05:03.347  1704  4084 V SplashScreenExceptionList: SplashScreen checking exception for package com.github.diegoberaldin.raccoonforlemmy.android (target sdk:34) -> false
05-24 10:05:03.351  1704  4084 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity bnds=[840,1675][1040,1959]} with LAUNCH_MULTIPLE from uid 10117 (BAL_ALLOW_ALLOWLISTED_COMPONENT) result code=0
05-24 10:05:03.359  2602  2651 V WindowManagerShell: Transition requested (#7468): android.os.BinderProxy@8c09fcd TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=1787 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity } baseActivity=ComponentInfo{com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} topActivity=ComponentInfo{com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} origActivity=null realActivity=ComponentInfo{com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} numActivities=1 lastActiveTime=1180134881 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@42b082} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{4b8f393 com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} launchCookies=[android.os.BinderProxy@3a8afd0] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 7468 }
05-24 10:05:03.369  1704 11245 D CoreBackPreview: Window{c4d01b8 u0 Splash Screen com.github.diegoberaldin.raccoonforlemmy.android}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@5ac8164, mPriority=0, mIsAnimationCallback=false}
05-24 10:05:03.386  1704  1739 V WindowManager: Sent Transition (#7468) createdAt=05-24 10:05:03.342 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=1787 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity } baseActivity=ComponentInfo{com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} topActivity=ComponentInfo{com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} origActivity=null realActivity=ComponentInfo{com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} numActivities=1 lastActiveTime=1180134881 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{80d8bc9 Task{a614315 #1787 type=standard A=10236:com.github.diegoberaldin.raccoonforlemmy.android}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{4d1f2ce com.github.diegoberaldin.raccoonforlemmy.android.MainActivity} launchCookies=[android.os.BinderProxy@eb355ef] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 7468 }
05-24 10:05:03.386  1704  1739 V WindowManager:         {WCT{RemoteToken{80d8bc9 Task{a614315 #1787 type=standard A=10236:com.github.diegoberaldin.raccoonforlemmy.android}}} m=OPEN f=NONE leash=Surface(name=Task=1787)/@0x137bfcd sb=Rect(0, 0 - 1080, 2520) eb=Rect(0, 0 - 1080, 2520) d=0},
05-24 10:05:03.391  1704  1752 I ActivityManager: Start proc 17959:com.github.diegoberaldin.raccoonforlemmy.android/u0a236 for next-top-activity {com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity}
05-24 10:05:03.417 17959 17959 W ziparchive: Unable to open '/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.arm64_v8a.dm': No such file or directory
05-24 10:05:03.417 17959 17959 W ziparchive: Unable to open '/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.arm64_v8a.dm': No such file or directory
05-24 10:05:03.417 17959 17959 W ziparchive: Unable to open '/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.en.dm': No such file or directory
05-24 10:05:03.417 17959 17959 W ziparchive: Unable to open '/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.en.dm': No such file or directory
05-24 10:05:03.418 17959 17959 W ziparchive: Unable to open '/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.xxhdpi.dm': No such file or directory
05-24 10:05:03.418 17959 17959 W ziparchive: Unable to open '/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.xxhdpi.dm': No such file or directory
05-24 10:05:03.420 17959 17959 D nativeloader: Configuring clns-4 for other apk /data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/base.apk:/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.arm64_v8a.apk:/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.en.apk:/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.xxhdpi.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/lib/arm64:/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/base.apk!/lib/arm64-v8a:/data/app/~~ApZdamfrCkM_6S5Jj6XfMQ==/com.github.diegoberaldin.raccoonforlemmy.android-_FJwVcD9fkv8uXukL-ukbw==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/da
05-24 10:05:03.585  1704  2074 D CoreBackPreview: Window{d31eff5 u0 com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@e22ac56, mPriority=0, mIsAnimationCallback=false}
05-24 10:05:03.975  1704  1739 I ActivityTaskManager: Displayed com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity for user 0: +630ms
05-24 10:05:04.001  1704  2789 I ImeTracker: com.github.diegoberaldin.raccoonforlemmy.android:34acc6bf: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
05-24 10:05:04.001  1704  2789 I ImeTracker: com.github.diegoberaldin.raccoonforlemmy.android:34acc6bf: onCancelled at PHASE_SERVER_SHOULD_HIDE
05-24 10:05:04.330  1704  4084 D CoreBackPreview: Window{c4d01b8 u0 Splash Screen com.github.diegoberaldin.raccoonforlemmy.android EXITING}: Setting back callback null
05-24 10:05:04.333  1704  2789 W InputManager-JNI: Input channel object 'c4d01b8 Splash Screen com.github.diegoberaldin.raccoonforlemmy.android (client)' was disposed without first being removed with the input manager!
05-24 10:05:08.654 17959 18026 D ProfileInstaller: Skipping profile installation for com.github.diegoberaldin.raccoonforlemmy.android
05-24 10:05:12.365  1704  2789 D CoreBackPreview: startBackNavigation currentTask=Task{a614315 #1787 type=standard A=10236:com.github.diegoberaldin.raccoonforlemmy.android}, topRunningActivity=ActivityRecord{d9864cc u0 com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity t1787}, callbackInfo=OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@e22ac56, mPriority=0, mIsAnimationCallback=false}, currentFocus=Window{d31eff5 u0 com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity}
05-24 10:05:12.416  1704  2789 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing input gesture for device 3 from [d31eff5 com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity (server), [Gesture Monitor] swipe-up (server)]
05-24 10:05:14.007  1704 11245 D CoreBackPreview: startBackNavigation currentTask=Task{a614315 #1787 type=standard A=10236:com.github.diegoberaldin.raccoonforlemmy.android}, topRunningActivity=ActivityRecord{d9864cc u0 com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity t1787}, callbackInfo=OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@e22ac56, mPriority=0, mIsAnimationCallback=false}, currentFocus=Window{d31eff5 u0 com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity}
05-24 10:05:14.074  1704 11245 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing input gesture for device 3 from [d31eff5 com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity (server), [Gesture Monitor] swipe-up (server)]
05-24 10:05:14.270 17959 17959 E AndroidRuntime: Process: com.github.diegoberaldin.raccoonforlemmy.android, PID: 17959
05-24 10:05:14.271  1704 11245 W ActivityTaskManager:   Force finishing activity com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity
05-24 10:05:14.275  1704  1740 I ActivityManager: Showing crash dialog for package com.github.diegoberaldin.raccoonforlemmy.android u0
05-24 10:05:14.312  1704  1740 D CoreBackPreview: Window{d8152f0 u0 Application Error: com.github.diegoberaldin.raccoonforlemmy.android}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@3c75820, mPriority=0, mIsAnimationCallback=false}
05-24 10:05:14.773  1704  1742 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{d9864cc u0 com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity t1787 f}}
05-24 10:05:14.773  1704  1742 W ActivityTaskManager: Activity pause timeout for ActivityRecord{d9864cc u0 com.github.diegoberaldin.raccoonforlemmy.android/.MainActivity t1787 f}}
05-24 10:05:14.846  1704  1739 V WindowManager:         {WCT{RemoteToken{80d8bc9 Task{a614315 #1787 type=standard A=10236:com.github.diegoberaldin.raccoonforlemmy.android}}} m=CLOSE f=NONE leash=Surface(name=Task=1787)/@0x137bfcd sb=Rect(0, 0 - 1080, 2520) eb=Rect(0, 0 - 1080, 2520) d=0},
05-24 10:05:16.879  1704  1740 D CoreBackPreview: Window{d8152f0 u0 Application Error: com.github.diegoberaldin.raccoonforlemmy.android}: Setting back callback null
05-24 10:05:16.879  1704 11245 I ActivityManager: Killing 17959:com.github.diegoberaldin.raccoonforlemmy.android/u0a236 (adj 900): crash
05-24 10:05:16.883  1704 11245 W InputManager-JNI: Input channel object 'd31eff5 com.github.diegoberaldin.raccoonforlemmy.android/com.github.diegoberaldin.raccoonforlemmy.android.MainActivity (client)' was disposed without first being removed with the input manager!
05-24 10:05:16.912  1704  1740 W InputManager-JNI: Input channel object 'd8152f0 Application Error: com.github.diegoberaldin.raccoonforlemmy.android (client)' was disposed without first being removed with the input manager!
05-24 10:05:16.955  1704  2788 V ActivityManager: Got obituary of 17959:com.github.diegoberaldin.raccoonforlemmy.android

If I have time today or this weekend, I may attempt to pinpoint the exact change that causes this, unless someone beats me to it. 
Thank you!

**Comment by diegoberaldin** [comment]
Thank you for the report and the time you dedicated to look for the actual cause!

It looks like an issue that has been fixed in #863, which is only included in the latest development build.

Unfortunately 1.10.2 contains some navigation bugs, like a nasty one that I fixed in #879 too, which occurred due to a race condition when opening a post detail and navigating back shortly after.

I am going to release the last development build of the month next week and 1.11.0 in June.

**Comment by N7-X** [comment]
Ah!  I never looked too deeply at the latest build, as the post contents weren't loading for me.  Looking forward to testing this in the next dev build! 

Speaking of which - I appreciate the way you regularly release those development builds, as it really helped with identifying the affected versions when troubleshooting. 

> After having been to KotlinConf this week there are so many things I would like to change in this project you can't imagine...

I was fully self-taught when it came to Android apps in Java, and never actually looked into Kotlin when it was added. 
Now I regret that, as I'd like to contribute to FOSS projects like this in my spare time.

**Comment by diegoberaldin** [comment]
Are there any requirements I am unaware of to contribute to this project,  any formal education, a degree or a certificate that you master the language or some specific technology?

This project is for fun and experimentation: I had never used SQLDelight before (because at work I've always used Room or Realm), Voyager or even Lyricist; this is the third time I use Koin (because I'm accustomed to Dagger/Hilt for dependency injection at work), and the list could go on...

So, if you want to contribute or maybe you want to learn something new that can be useful IRL and want to experiment:

1. don't hesitate to ask for support I'm here for that, even if you need to install Android Studio from scratch and configure everything 
 2. pull requests have to be reviewed, tested and approved
3. in case anything breaks unexpectedly it can be fixed or reverted later. 

The only limit is time (I contribute in my spare time too) but, again, there are no requirements. Even if one day you decide "ok, I'm out" or disappear from one day to the next one without even telling (already happened). We're free do do as we like so don't feel constrained by anything, "freedom" in open source means you have no obligations whatsoever.

**Comment by diegoberaldin** [comment]
Since I confirm this does not happen any more in 1.11.0-20240520-pre (I've come back home and tested it more thoroughly) I'll close it.

Thanks for the report and the accurate description, hope to hear from you soon!

**Comment by N7-X** [comment]
> Are there any requirements I am unaware of to contribute to this project, any formal education, a degree or a certificate that you master the language or some specific technology?

Fair points...  It will probably take me time to get up to speed on how the project is organized before I feel comfortable enough to start formally contributing. 
Ideally, I want to understand approximately how things are laid out, as it helps me problem solve and get that big picture view. 

> The only limit is time (I contribute in my spare time too) but, again, there are no requirements. Even if one day you decide "ok, I'm out" or disappear from one day to the next one without even telling (already happened). We're free do do as we like so don't feel constrained by anything, "freedom" in open source means you have no obligations whatsoever.

Yeah, time is the biggest limit for me.  It might take a while for me to actually respond sometimes (like now!) but I don't plan on vanishing, as communication is important to me. 

> Since I confirm this does not happen any more in 1.11.0-20240520-pre (I've come back home and tested it more thoroughly) I'll close it.

Nice!  Thanks for taking the time to look into it and confirm that it is indeed fixed. 
I started looking into why the posts weren't loading on the master branch, but I ran out of time before I had wrapped my head around the layout. 

> Thanks for the report and the accurate description, hope to hear from you soon!
Glad to help!  Hope all is well, and thanks again for the speedy resolution and responses

**Comment by diegoberaldin** [comment]
Take your time... for more technical information about the code (the rationale behind some choices, structure, architectural patterns, etc.) there is a short description in the [CONTRIBUTING.md](https://github.com/diegoberaldin/RaccoonForLemmy/blob/master/CONTRIBUTING.md) and a somewhat more detailed one in the [technical manual](https://diegoberaldin.github.io/RaccoonForLemmy/tech_manual/main). But reach out to me on Matrix (or Discord, or whatever) if you prefer asking questions instead of looking at a wall of text.
