### ISSUE TITLE
Cannot unban an instance

### ISSUE THREAD

**Issue by somesortofrescuetoaster** [diegoberaldin/RaccoonForLemmy#883]
**Describe the bug**
I intended to block a community, and accidentally clicked "block instance" instead of "block" (which I also think should be renamed to "block community" to better distinguish from "block instance").  When I go to my bans and filters and click  "unban" in the three dot menu next to the blocked instance, nothing happens.

**To Reproduce**
1. Block instance
2. Go to settings.
3. Click three dot menu next to blocked instance and select "unban"
4. Nothing happens - Instance is still blocked

**Expected behavior**
Clicking unban instance should remove the instance from the list and I should be able to view posts from the instance again.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: stock android
 - Version 1.10.2 (99)

**Additional context**
I tested this by purposely blocking another instance, and I also could not remove this second instance from blocklist.  I can remove the blocked instances by going to my lemmy instance website.  If specific instances are needed: my account is on lemm.ee and I accidently blocked lemmy.zip and then purposely blocked reddthat.com to test bug again.

**Comment by diegoberaldin** [comment]
Thanks, crystal clear explanation... I'll look into it asap.
